name: fitnfit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: any
  intl: any
  flutter_vector_icons: ^2.0.0
  youtube_player_flutter: ^9.0.1
  chewie: ^1.8.1
  flutter_inappwebview: ^6.0.0
  pedometer: ^4.0.1
  chat_gpt_flutter: ^1.0.16
  fluttertoast: ^8.2.5
  country_code_picker: ^3.0.0
  infinite_listview: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.2.6
  image_picker: any
  permission_handler: ^11.3.1
  flutter_widget_from_html_core: ^0.14.12
  flutter_tts: ^4.0.2
  draggable_bottom_sheet: ^1.0.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_bounce: ^1.1.0
  card_swiper: ^3.0.1
  simple_pip_mode: ^0.8.0
  share_plus: ^9.0.0

  #localizations
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^25.2.4
  path_provider: ^2.1.3
  shared_preferences_android: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Flag/